[package]
name = "numfst"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
clap = { version = "3", features = ["derive"] }
env_logger = "0.8.4"
fst = "0.4.7"
log = "0.4.14"
